// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block                    = require("bs-platform/lib/js/block.js");
var Curry                    = require("bs-platform/lib/js/curry.js");
var React                    = require("react");
var ReasonReact              = require("reason-react/src/ReasonReact.js");
var SiteHeader$ReactTemplate = require("./SiteHeader.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("App");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var match = self[/* state */2][/* org */0];
      var match$1 = self[/* state */2][/* repo */1];
      return React.createElement("div", undefined, React.createElement("style", undefined, "\n          body {\n            margin: 0;\n            padding: 0;\n            font-family: sans-serif;\n          }\n        "), ReasonReact.element(/* None */0, /* None */0, SiteHeader$ReactTemplate.make((function (org) {
                            return Curry._1(self[/* send */4], /* SetOrg */Block.__(0, [org]));
                          }), (function (repo) {
                            return Curry._1(self[/* send */4], /* SetRepo */Block.__(1, [repo]));
                          }), /* array */[])), React.createElement("div", undefined, "Org", match ? match[0] : null), React.createElement("div", undefined, "Repo", match$1 ? match$1[0] : null));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* org : None */0,
              /* repo : None */0
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (action.tag) {
        return /* Update */Block.__(0, [/* record */[
                    /* org */state[/* org */0],
                    /* repo : Some */[action[0]]
                  ]]);
      } else {
        return /* Update */Block.__(0, [/* record */[
                    /* org : Some */[action[0]],
                    /* repo */state[/* repo */1]
                  ]]);
      }
    });
  return newrecord;
}

exports.str       = str;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
