// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React                    = require("react");
var ReasonReact              = require("reason-react/src/ReasonReact.js");
var SiteHeader$ReactTemplate = require("./SiteHeader.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("App");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, React.createElement("style", undefined, "\n          body {\n            margin: 0;\n            padding: 0;\n            font-family: sans-serif;\n          }\n        "), ReasonReact.element(/* None */0, /* None */0, SiteHeader$ReactTemplate.make(/* array */[])));
    });
  return newrecord;
}

exports.str       = str;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
