// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("bs-json/src/Json_decode.js");

function parse_repo_list(json) {
  return /* record */[/* repos */Json_decode.field("repos", (function (param) {
                  return Json_decode.list(Json_decode.string, param);
                }), json)];
}

function fetchAll() {
  return fetch("http://localhost:3000/api/repos").then((function (prim) {
                    return prim.json();
                  })).then((function (json) {
                  return Promise.resolve(parse_repo_list(json));
                })).then((function (repo_list) {
                return Promise.resolve(repo_list[/* repos */0]);
              }));
}

exports.parse_repo_list = parse_repo_list;
exports.fetchAll        = fetchAll;
/* No side effect */
