// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                  = require("bs-platform/lib/js/list.js");
var $$Array               = require("bs-platform/lib/js/array.js");
var Block                 = require("bs-platform/lib/js/block.js");
var Curry                 = require("bs-platform/lib/js/curry.js");
var React                 = require("react");
var Glamor                = require("bs-glamor/src/glamor.js");
var ReasonReact           = require("reason-react/src/ReasonReact.js");
var OrgData$ReactTemplate = require("./OrgData.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("SiteHeader");

var root = Glamor.css(/* :: */[
      Glamor.display("flex"),
      /* :: */[
        Glamor.backgroundColor("#F2F2F2"),
        /* :: */[
          Glamor.border("1px solid #ddd"),
          /* :: */[
            Glamor.height("50px"),
            /* :: */[
              Glamor.alignItems("center"),
              /* :: */[
                Glamor.padding("0 20px"),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var Styles = /* module */[/* root */root];

function make() {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (self) {
      OrgData$ReactTemplate.fetchAll(/* () */0).then((function (orgs) {
              Curry._1(self[/* send */4], /* LoadOrgs */[orgs]);
              return Promise.resolve(/* () */0);
            }));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (param) {
      var state = param[/* state */2];
      return React.createElement("div", {
                  className: root
                }, React.createElement("label", undefined, "Org", React.createElement("select", undefined, $$Array.of_list(List.map((function (org) {
                                    return React.createElement("option", undefined, org);
                                  }), state[/* orgs */0])))), React.createElement("label", undefined, "Repo", React.createElement("select", undefined, $$Array.of_list(List.map((function (org) {
                                    return React.createElement("option", undefined, org);
                                  }), state[/* orgs */0])))));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* orgs : [] */0];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [/* record */[/* orgs */action[0]]]);
    });
  return newrecord;
}

exports.str       = str;
exports.component = component;
exports.Styles    = Styles;
exports.make      = make;
/* component Not a pure module */
