// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Spacer");

function make($staropt$star, $staropt$star$1, _) {
  var width = $staropt$star ? $staropt$star[0] : "";
  var height = $staropt$star$1 ? $staropt$star$1[0] : "";
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  style: {
                    height: height,
                    width: width
                  }
                });
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
