// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

var listToElement = $$Array.of_list;

function getTarget($$event) {
  return $$event.target;
}

exports.listToElement = listToElement;
exports.getTarget     = getTarget;
/* No side effect */
